### ISSUE TITLE
upstream request timeout

### ISSUE THREAD

**Issue by herawais** [OdooOps/dockery-odoo#49]
Sometimes the site work fine but sometimes this error
upstream request timeout
How to increase the timeout ?
I tried to increase the connect_timeout parameter in envoy.yaml but not worked.

**Comment by blaggacao** [comment]
@herawais Thanks for you question.

Odoo is known for having long running synchronous (blocking) requests.

The problem is fundamentally with Odoo Framework doing this.

Typical candidates are gathering a huge report datasets or rendering a PDF.

- As for PDF you _could_ serve the wkhtmltopdf renderer as a different service (yes it's possible, but few have attempted).
If you'd want go down this road, please consider making a draft PR here early on so I might give hands on feedback.

- As for the long running report queries, I suggest you trace them down properly to understand in detail if you want to allow for the odoo backend to be slow in responding (as opposed to server hanging or overloaded - which _is_ an unhealthy backend).

The timeout is entirely enforced by the envoyproxy component, so I'd suggest you [skim their documentation](https://www.envoyproxy.io/docs) for it to see how it can be tweaked. Mayby [per route timeouts](https://www.envoyproxy.io/docs/envoy/v1.15.0/faq/configuration/timeouts.html?highlight=timeout#route-timeouts)?

**Comment by herawais** [comment]
Thanks @blaggacao
